Rails.application.config.assets.precompile += %w( certified.css )
Rails.application.config.assets.precompile += %w( bootstrap/css/bootstrap.min.css )
Rails.application.config.assets.precompile += %w( fonts/fonts.css )
Rails.application.config.assets.precompile += %w( vendors.js )
Rails.application.config.assets.precompile += %w( app.f67f6ba6488d65055834.js )
