Rails.application.config.assets.precompile += %w( certified.css )
Rails.application.config.assets.precompile += %w( bootstrap/css/bootstrap.min.css )
Rails.application.config.assets.precompile += %w( fonts/fonts.css )
Rails.application.config.assets.precompile += %w( vendors.js )
Rails.application.config.assets.precompile += %w( app.155efb927dc5fb80db7c.js )
