version: '2'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: dev
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: training
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file: .env
    volumes:
      - .:/opt/training
    ports:
      - "3000:3000"
    depends_on:
      - db
