# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 415dd6b14fa2ef950494b077e1b90017988c4545a948c1f0dfdbe991951147efb26018a46ef37616c100ff4ae227bff9c4653c973f1f129a4b8c3c2cd9634f24

test:
  secret_key_base: e06404b032fa8a0c3fb2e503aee993a9444bb703b87050b110f9b239056a5a2a6b10740acb1e95d39312456059b77456de57c7bed148d1f605b7a8f64a2036c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
